services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - redis
      - postgres
    tty: true
    stdin_open: true
    env_file:
      - .env.devcontainer
  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eliminator_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
